@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.cazsius.solcarrot.communication;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;